import type { IconConfig } from '../../../types/tuner';

export const DEFAULT_CONFIG: Omit<IconConfig, 'subject' | 'category' | 'source'> = {
  circle_color: [0.5, 0.5, 0.5],
  circle_border_width: 0.75,
  circle_border_color: [0, 0, 0],
  id_box_height: 2.3,
  id_box_width_ratio: 0.41,
  id_box_border_width: 0.35,
  id_box_y_offset: 0,
  no_id_box: false,
  id_font_size: 3.9,
  img_scale_ratio: 0.70,
  img_x_offset: 0,
  img_y_offset: 0,
  brand_text: '',
  brand_font_size: 1.8,
  brand_y_offset: -3.2,
  brand_x_offset: -0.2,
  model_font_size: 2.2,
  model_y_offset: 2.5,
  model_x_offset: -0.2,
  model_text_override: null,
  model_uppercase: false,
  font_name: '/Helvetica-Bold',
  text_color: [1, 1, 1],
  id_text_color: null,
  no_image: false,
  image_path: null,
  layer_order: ['gear_image', 'brand_text', 'model_text'],
  id_preview: 'j100',
};
